# Generated by Django 4.2.6 on 2023-11-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_category_restaurant_restaurantmenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='MultiCuisine', max_length=100),
        ),
    ]
