# Generated by Django 4.2.6 on 2023-11-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_restaurant_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenu',
            name='category',
        ),
    ]
